version: '3.9'

services:
  postgres:
    image: postgres:16-alpine
    container_name: localize-postgres
    environment:
      POSTGRES_DB: ${DB_NAME:-localize}
      POSTGRES_USER: ${DB_USERNAME:-localize}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-localize}
    ports:
      - "5438:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME:-localize}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  postgres-data:
    driver: local
